[package]
name = "spark-starlight"
version = "0.1.0"
edition = "2021"

[dependencies]
spark-inference = { path = "../spark-inference" }
spark-media = { path = "../spark-media" }

mimalloc = "0.1.43"
bitvec = "1.0.1"

anyhow = "1.0.95"
log = "0.4.22"
tklog = "0.2.9"