[package]
name = "spark-media"
version = "0.1.0"
edition = "2021"

[dependencies]
spark-ffmpeg = { path = "../spark-ffmpeg" }

anyhow = "1.0.97"
log = "0.4.27"

parking_lot = { version = "0.12.3", features = ["nightly"] }
hashbrown = "0.15.2"
