[package]
name = "spark-ffmpeg"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.70.1"

[dependencies]
spark-proc_macro = { path = "../spark-proc_macro" }

anyhow = "1.0.86"
paste = "1.0.15"
num_enum = "0.7.3"
rayon = "1.10.0"

image = "0.25.2"
ndarray = "0.16.1"