[package]
name = "spark-ffmpeg"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.71.1"
rayon = "1.10.0"
convert_case = "0.6.0"

[dependencies]
spark-proc_macro = { path = "../spark-proc_macro" }

anyhow = "1.0.95"
num_enum = "0.7.3"
rayon = "1.10.0"
