[package]
name = "spark-inference"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
cudarc = { version = "0.12.1", features = ["cuda-12050", "cudnn"] }

rayon = "1.10.0"
bitvec = "1.0.1"

anyhow = "1.0.92"

blas-src = { version = "0.10", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }

spark-ffmpeg = { path = "../spark-ffmpeg" }
spark-media = { path = "../spark-media" }

[dependencies.ndarray]
version = "0.16.1"
features = ["rayon", "matrixmultiply-threading", "blas"]

[dependencies.ort]
git = "https://github.com/pykeio/ort.git"
features = ["tensorrt", "cuda", "load-dynamic", "ndarray"]